version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    depends_on:
      - db
    environment:
      - PORT=${PORT:-5000}
      - PG_PORT=${PG_PORT:-5432}
      - PG_HOST=${PG_HOST:-db}
      - PG_USER=${PG_USER:-admin}
      - PG_PASSWORD=${PG_PASSWORD:-admin123}
      - PG_DATABASE=${PG_DATABASE:-task_db}
      - JWT_SECRET=${JWT_SECRET:-beleiveinurself}
    networks:
      - app-network

  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: ${PG_USER:-admin}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-admin123}
      POSTGRES_DB: ${PG_DATABASE:-task_db}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PG_PORT:-5432}:${PG_PORT:-5432}"
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
